### DISCUSSION TITLE
Should existing plugins that add utilities work with NativeWind?

### DISCUSSION THREAD

**Discussion by jgornick** [nativewind/nativewind#148] [Q&A] [answered]
Hey folks!

I'm trying to provide aliases for single or groups of tailwind classes using the https://github.com/softwarecrafts/tailwind-component-classes plugin. However, when I build, the alias classes are not being added to my `NativeWindStyleSheet` styles. 

For example, I want to alias`border-purple-default` to `border-purple-900' and I do so like this in configuration:

```javascript
module.exports = {
  plugins: [require('tailwind-component-classes')],
  utilities: {
    'border-purple-default': 'border-purple-900',
  },
}
```

For my CSS build, the `border-purple-default` classes is added to my stylesheet with the same declarations provided by the `border-purple-900` class, but it's not when compiling the NativeWind stylesheet.

My CSS output looks like:

```css
.border-purple-900 {
  --tw-border-opacity: 1;
  border-color: rgb(88 28 135 / var(--tw-border-opacity))
}

.border-purple-default {
  --tw-border-opacity: 1;
  border-color: rgb(88 28 135 / var(--tw-border-opacity))
}
```

Thoughts?
