### ISSUE TITLE
expo export -p web stuck on platforms: linux/arm64/v8 working fine on platforms: linux/amd github action

### ISSUE THREAD

**Issue by milon27-pyng** [nativewind/nativewind#1138]
"expo": "51.0.37",
"nativewind": "4.1.16",
"react": "18.2.0",
"react-dom": "18.2.0",

"engines": {
        "node": ">=20",
        "pnpm": "8.12.1"
    }

## github action file

```yml
    build:
         runs-on: ubuntu-latest
         steps:
             - name: Checkout code
               uses: actions/checkout@v3

             - name: Set up Docker Buildx
               uses: docker/setup-buildx-action@v1

             - name: Log in to GitHub Container Registry
               uses: docker/login-action@v3
               with:
                   registry: ghcr.io
                   username: ${{ github.actor }}
                   password: ${{ secrets.GITHUB_TOKEN }}

             - name: Build and push Docker image
               uses: docker/build-push-action@v6
               with:
                   context: .
                   target: prod
                   push: true
                   platforms: linux/arm64/v8 #  Specify the target platform for oracle arm, default is linux/amd64
                   tags: ghcr.io/${{ github.repository }}/pm-client:latest


```

if I don't specify `platforms: linux/arm64/v8` it works fine

## Dockerfile

```
# # ------------------ build -------------------
FROM node:20.15.1-alpine as build
RUN npm install -g pnpm@8.12.1

WORKDIR /app

COPY . .
RUN pnpm install

# web:build = expo export -p web
RUN pnpm web:build 


# # # ------------------ deploy -------------------
FROM nginx:alpine as prod

# Copy your custom Nginx configuration file
COPY ./.nginx/nginx.conf /etc/nginx/conf.d/default.conf

# Expose port 80 for incoming HTTP traffic
EXPOSE 80

COPY --from=build /app/dist ./usr/share/nginx/html

```
